name: "Build Image"
on:
  push:
    branches:
      - not-existing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 #SHA for v3.0.0
      - name: Login to DockerHub
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 #SHA for v1.14.1
        with:
          username: drollinger
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push webapp
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a #SHA for v2.10.0
        with:
          file: Dockerfile
          push: true
          tags: drollinger/automation-testing:latest
