name: "Sanity Tests"
on: [push, pull_request] 

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 #SHA for v3.0.0
      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.1
      - name: Run Linter
        run: deno lint

  
